FROM ubuntu:latest

LABEL poem = "about birtch"

WORKDIR /app

#RUN apt update

COPY . .

COPY id_rsa.pub /root/.ssh/authorized_keys

RUN apt update -y

RUN git clone

RUN apt-get install python3-pip -y

RUN pip install black

ENTRYPOINT ["black", "." , "--check"]
