FROM ubuntu:22.04
WORKDIR /app
#RUN apt update
COPY . .

COPY id_rsa.pub /root/.ssh/authorized_keys

RUN apt update -y
RUN apt-get install python3-pip -y
RUN pip install black

ENTRYPOINT ["black", "." , "--check"]
